name: 'wildfire_dbt'
version: '1.0.0'
config-version: 2

profile: 'wildfire_dbt'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wildfire_dbt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
