wildfire_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: sx70385.us-east-2.aws
      user: Vishnu14
      password: Vishnu@project14
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: WILDFIRE_DB
      schema: ANALYTICS
      threads: 4
